name: Laplace-Net
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - plotly=5.24.1
  - pandas=2.2.3
  - scipy=1.14.1
  - optuna=4.1.0
  - scikit-learn=1.6.1
  - psutil=6.1.1
  - pynvml=12.0.0
  - tqdm=4.67.1
  - yaml=0.2.5
  - optuna-dashboard=0.17.0
  - seaborn=0.13.2