# ILT parameters
ilt_terms:
  default: 77
  search_space:
    type: "int"
    low: 33
    high: 79
    step: 2 #have to be odd
ilt_alpha:
  default: 0.002
  search_space:
    type: "float"
    low: 0.00001
    high: 0.0101
    step: 0.00005
ilt_scale:
  default: 2.6
  search_space:
    type: "float"
    low: 1
    high: 3
    step: 0.1
ilt_shift:
  default: 8.0
  search_space:
    type: "float"
    low: 0.5
    high: 10.0
    step: 0.1

laplace_scaling_factor:
  default: 60.0
  search_space:
      type: "float"
      low: 10
      high: 500.0
      step: 10.0

LP_trafo_type:
  default: "FFLT"
  search_space:
    type: "categorical"
    choices: ["FFLT", "DLT"]

grid_limits:
  default: [-1, 1]

## Input Excitation Network parameters
#ie_hidden_size:
#  default: 32
#  search_space:
#    type: "int"
#    low: 16
#    high: 128
#    step: 16
#ie_num_layers:
#  default: 2
#  search_space:
#    type: "categorical"
#    choices: [1, 2, 3]
#ie_activation:
#  default: "tanh"
#  search_space:
#    type: "categorical"
#    choices: ["tanh", "sigmoid"]

# Transfer Function Network parameters
tf_hidden_dim:
  default: 128
  search_space:
    type: "int"
    low: 32
    high: 192
    step: 16
tf_num_hidden_layers:
  default: 4
  search_space:
    type: "int"
    low: 1
    high: 6
    step: 1
tf_activation:
  default: "tanh"
  search_space:
    type: "categorical"
    choices: ["tanh","sigmoid","softsign","silu"]
tf_process_all_terms:
  default: true

use_laplace_scaling:
  default: true

steps:
  default: 10
  search_space:
    type: "int"
    low: 1
    high: 10
    step: 1





# Initial State Network parameters
is_order_dim:
  default: 1
  search_space:
    type: "int"
    low: 1
    high: 4
    step: 1
is_RNN_hidden_dim:
  default: 40
  search_space:
    type: "int"
    low: 8
    high: 64
    step: 4
is_RNN_num_layers:
  default: 3
  search_space:
    type: "int"
    low: 1
    high: 5
    step: 1

# Global training parameter for the model
learning_rate:
  default: 0.000287
  search_space:
    type: "loguniform"
    low: 1e-6
    high: 1e-2
